// Code generated by "stringer --type UserPresence --linecomment"; DO NOT EDIT.

package slackclient

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Active-1]
	_ = x[Away-2]
	_ = x[Auto-3]
}

const _UserPresence_name = "unknownactiveawayauto"

var _UserPresence_index = [...]uint8{0, 7, 13, 17, 21}

func (i UserPresence) String() string {
	if i >= UserPresence(len(_UserPresence_index)-1) {
		return "UserPresence(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserPresence_name[_UserPresence_index[i]:_UserPresence_index[i+1]]
}
